### ISSUE TITLE
Carousel CSS updates

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1203]
## Expected behaviour

![Screen Shot 2019-07-12 at 11 27 28 am](https://user-images.githubusercontent.com/1926461/61100424-7328e900-a4a9-11e9-9937-88409614179a.png)

## Changes
Carousel Panel
- [x] Merge panel and footer into a single component
- [ ] Given above, the horizontal padding for carousel container can be removed
- [x] Set background colour to UoM Navy #094183 (and invert text elements to white)

Transition Bar
- [x] Set progress colour to Navy Mid 2 #5D82AD
- [x] Set background colour to Navy Light #F2F5F9

Secondary Stories
- [x] Increase flex-bases of .carousel__aside to 40%
- [x] Increase .carousel__navigation-link horizontal padding to 16px
- [x] Set colour to White
- [x] Set featured story highlight to White
- [x] Set featured story text colour to Navy #094183
- [x] Reduce divider height to 1px
- [x] Set divider colour to Navy Mid 2 #5D82AD
- [x] Set font size to 19.2px
- [ ] Set line height to 25px

Featured Story Heading
- [x] Set font family to Source Sans
- [x] Set font weight to Bold / 700
- [x] Set font size to 33.2px 
- [ ] Set line height to 44.85px
- [x] Set colour to White
- [x] Remove hyperlink colouration (atm the heading gets coloured like a regular hyperlink, but it should remain white)

Featured Story Description
- [ ] Reduce sample text to ~3 lines of text (these should be brief, and not full stories)
- [x] Set font size to 16px
- [ ] Set line height to 25px

CTA
- [ ] Set button fill to UoM Navy (or clear?) #094183
- [ ] Set border to Navy Mid 2 #5D82AD
- [ ] Set text colour to White
- [ ] Set hover fill to UoM Navy Secondary #033A7B

## Possible solution

Apply these changes.

```
@media (min-width: 769px) {
  .carousel__footer {
    /* height: 115px; */
  }
}

@media (min-width: 769px) {
  .carousel__panel {
    /* position: absolute; */
    /* bottom: 3rem; */
  }
}

@media (min-width: 769px) {
  .carousel__description {
    /* height: 6.25rem; */
  }
}

@media (min-width: 769px) {
  .carousel__aside {
    /* flex-basis: 30%; */
    flex-basis: 40%;
  }
}

.carousel__panel {
  /* background: #f2f5f9; */
  background: #094183;
}

.carousel__description {
  /* color: #000; */
  color: #fff;
}

a {
  /* color: #0f5b72; */
  color: #fff;
}

.carousel__navigation-link--active {
  /* background: #094183; */
  /* color: #fff !important; */
  background: #fff;
  color: #094183 !important;
}

.carousel__navigation-link {
  /* color: #094183; */
  color: #fff;
}

.carousel__controls-item {
  /* color: #094183; */
  color: #fff;
}
```
