### ISSUE TITLE
Reorganize the pattern library Storybook 

### ISSUE THREAD

**Issue by meligatt** [unimelb/pattern-lib#896]
## The problem:
the storybook UI development environment of Pattern library is not consistent in the way it shares the  markup of the the usage of each component. 
In some stories the code available in the "read me" section is the html markup (source code) of the components, and sometimes is the template markup in which the component was mounted. 
- example: 
1) sharing HTML markup of the component: 
`Notice` component:
```http://localhost:7002/?selectedKind=Notice&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel```

Instead of sharing How to mount `Notice` component and what props/children is expecting, like this:
```
<Notice>
    <span> <strong>Notice!</strong>this are children tags passed to notice component</span>
  </Notice>
```
This inconsistencies makes difficult to keep track what markup has been copied (or spread) across the CMS. 

## Todo
- [ ] Understand how the CMS team is using the pattern library (copying the html markup of the components mount passing props)
- [ ] Standardise the way the markup is being share in story book, (html markup OR component usage)
- [ ] Add examples of usage separate of the markup itself. (see examples like `https://auth0-cosmos.now.sh/docs/#/component/heading`)

**Comment by jaredh-um** [comment]
Agree that this is not really worth sinking time into unless we are intending to maintain Gen 2 long-term, which is not the case at this stage. Closing.
